os: linux
dist: trusty
language: cpp
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install build-essential
- sudo apt-get install llvm
- sudo apt-get install valgrind
compiler:
- g++
script: ./travis.sh
